apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: shrink-core-pipeline
  namespace: cp4i
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
  workspaces:
    - name: git-source
  tasks:
    - name: clone-git-source
      retries: 2
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "https://github.com/callumpjackson/cloud-native-integration.git"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "main"
      workspaces:
        - name: output
          workspace: git-source

    # shrink ACE Core
    - name: shrink-ace-core
      retries: 2
      runAfter:
        - clone-git-source
      taskRef:
        name: run-script
      params:
        - name: script
          value: "ace/decrementServer.sh"
        - name: params
          value: " cp4i echo"
      workspaces:
        - name: git-source
          workspace: git-source
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: shrink-core-pipeline-triggertemplate
  namespace: cp4i
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: shrink-core-pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: shrink-core-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: git-source
            persistentvolumeclaim:
              claimName: git-source-workspace
        params:
          - name: imageTag
            value: $(uid)
        timeout: "20m"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: shrink-core-pipeline-event-listener
  namespace: cp4i
spec:
  serviceAccountName: pipeline
  triggers:
    - template:
        ref: shrink-core-pipeline-triggertemplate
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: shrink-core-pipeline-event-listener
  name: el-shrink-core-pipeline-trigger-route
  namespace: cp4i
spec:
  host: ""
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-shrink-core-pipeline-event-listener
    weight: null
