apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-source-workspace
  namespace: cp4i
spec:
  storageClassName: "cp4i-file-performance-gid"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
